[build-system]
requires = ["setuptools>=42", 
            "torch~=1.11.0", 
            "torchvision~=0.12.0", 
            "torch_snippets", 
            "pycocotools", 
            "numpy", 
            "Pillow"]
build-backend = "setuptools.build_meta"
